### ISSUE TITLE
Add a try-catch for display update

### ISSUE THREAD

**Issue by federico3** [federico3/sky-finder#60]
App keeps crashing while updating the display due to a finicky i2c bus. Ok, it's an hardware issue, but it's annoying.

```
Jan 28 11:40:14 trovastelle2 systemd[1]: Started Trovastelle service.
Jan 28 11:43:54 trovastelle2 trovastelle.sh[4122]: Slow display update prop is False
Jan 28 11:43:54 trovastelle2 trovastelle.sh[4122]: Traceback (most recent call last):
Jan 28 11:43:54 trovastelle2 trovastelle.sh[4122]:   File "/home/pi/trovastelle/src/celestial_compass/trovastelle.py", line 451, in <module>
Jan 28 11:43:54 trovastelle2 trovastelle.sh[4122]:     asyncio.run(ts.run(),debug=_debug)
Jan 28 11:43:54 trovastelle2 trovastelle.sh[4122]:   File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
Jan 28 11:43:54 trovastelle2 trovastelle.sh[4122]:     return loop.run_until_complete(main)
Jan 28 11:43:54 trovastelle2 trovastelle.sh[4122]:   File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
Jan 28 11:43:54 trovastelle2 trovastelle.sh[4122]:     return future.result()
Jan 28 11:43:54 trovastelle2 trovastelle.sh[4122]:   File "/home/pi/trovastelle/src/celestial_compass/trovastelle.py", line 412, in run
Jan 28 11:43:54 trovastelle2 trovastelle.sh[4122]:     await cc_task
Jan 28 11:43:54 trovastelle2 trovastelle.sh[4122]:   File "/home/pi/trovastelle/src/celestial_compass/compass.py", line 174, in run
Jan 28 11:43:54 trovastelle2 trovastelle.sh[4122]:     await main_task
Jan 28 11:43:54 trovastelle2 trovastelle.sh[4122]:   File "/home/pi/trovastelle/src/celestial_compass/compass.py", line 239, in _run_main
Jan 28 11:43:54 trovastelle2 trovastelle.sh[4122]:     self.display_controller.display_observable_data(
Jan 28 11:43:54 trovastelle2 trovastelle.sh[4122]:   File "/home/pi/trovastelle/src/celestial_compass/display_manager.py", line 269, in display_o>
Jan 28 11:43:54 trovastelle2 trovastelle.sh[4122]:     self._display_text_in_box(
Jan 28 11:43:54 trovastelle2 trovastelle.sh[4122]:   File "/home/pi/.local/lib/python3.9/site-packages/luma/core/render.py", line 43, in __exit__
Jan 28 11:43:54 trovastelle2 trovastelle.sh[4122]:     self.device.display(self.image)
Jan 28 11:43:54 trovastelle2 trovastelle.sh[4122]:   File "/home/pi/.local/lib/python3.9/site-packages/luma/oled/device/__init__.py", line 225, i>
Jan 28 11:43:54 trovastelle2 trovastelle.sh[4122]:     self.data(list(buf))
Jan 28 11:43:54 trovastelle2 trovastelle.sh[4122]:   File "/home/pi/.local/lib/python3.9/site-packages/luma/core/device.py", line 55, in data
Jan 28 11:43:54 trovastelle2 trovastelle.sh[4122]:     self._serial_interface.data(data)
Jan 28 11:43:54 trovastelle2 trovastelle.sh[4122]:   File "/home/pi/.local/lib/python3.9/site-packages/luma/core/interface/serial.py", line 125, >
Jan 28 11:43:54 trovastelle2 trovastelle.sh[4122]:     write(list(data[i:i + block_size]))
Jan 28 11:43:54 trovastelle2 trovastelle.sh[4122]:   File "/home/pi/.local/lib/python3.9/site-packages/luma/core/interface/serial.py", line 134, >
Jan 28 11:43:54 trovastelle2 trovastelle.sh[4122]:     self._bus.i2c_rdwr(self._i2c_msg_write(self._addr, [self._data_mode] + data))
Jan 28 11:43:54 trovastelle2 trovastelle.sh[4122]:   File "/home/pi/.local/lib/python3.9/site-packages/smbus2/smbus2.py", line 658, in i2c_rdwr
Jan 28 11:43:54 trovastelle2 trovastelle.sh[4122]:     ioctl(self.fd, I2C_RDWR, ioctl_data)
Jan 28 11:43:54 trovastelle2 trovastelle.sh[4122]: OSError: [Errno 121] Remote I/O error
```

**Comment by federico3** [comment]
Actually we have already done that but OSError is not caught...

**Comment by federico3** [comment]
https://www.geeksforgeeks.org/handling-oserror-exception-in-python/

https://stackoverflow.com/questions/63444603/catch-a-specific-oserror-exception-in-python-3

https://docs.python.org/3/library/exceptions.html#os-exceptions

**Comment by federico3** [comment]
We were looking in the wrong place. Gemini explains:

The call to `self._display_text_in_box` wasn't actually skipped—**it executed and finished successfully.** What you are seeing is a specific quirk of how Python tracebacks handle context managers (the `with` statement).

Here is exactly what is happening under the hood:

### 1. The `luma` Canvas Context Manager
In the `luma.oled` library, updating the display is typically handled using a `canvas` context manager. Your code in `display_calibration_data` likely looks something like this:

```python
with canvas(self.device) as draw:
    # ... maybe some other drawing commands ...
    self._display_text_in_box(
        # ... arguments ...
    )
```

Inside this `with` block, all drawing operations (like your text box) are just modifying an image buffer in the device's memory. They don't interact with the hardware yet. 

### 2. The `__exit__` Method
When the `with` block finishes, Python automatically calls the `__exit__` method of the `canvas` object. In the `luma` library, the `__exit__` method is responsible for taking that finished image buffer and pushing it over the I2C bus to your physical OLED screen. 

You can see this exact handoff in your traceback:
> `File "/home/pi/.local/lib/python3.9/site-packages/luma/core/render.py", line 43, in __exit__`
> `self.device.display(self.image)`

### 3. The Traceback Illusion
When an exception occurs *inside* a context manager's `__exit__` method, Python needs to attach a line number to it. By design, Python points the traceback to the **last executed statement inside the `with` block**. 

Because `self._display_text_in_box` was the last line of code inside your `with canvas(...)` block, Python essentially says: *"Right after this line finished, the block exited and crashed."* It looks like the traceback skips the inner workings of `_display_text_in_box` because that function didn't crash; it did its job perfectly and returned control back to the context manager.

### The Actual Culprit: `OSError: [Errno 5]`
Your code logic is perfectly fine. The crash happened entirely in hardware communication. 

`OSError: [Errno 5] Input/output error` during an `i2c_rdwr` (I2C read/write) means your Raspberry Pi lost communication with the BNO055 sensor or the OLED screen. When `luma` tried to send the final pixel data to the display over the I2C bus, the hardware didn't acknowledge it. This is typically caused by:
* Loose jumper wires.
* Electromagnetic interference (EMI) on the I2C lines.
* Insufficient power delivery to the display or sensor.
* I2C address conflicts or bus locking up.

**Comment by federico3** [comment]
Resolved in 0e22bac97fa8abdcb9351bf17b921ebc2838f073

**Comment by federico3** [comment]
```
2026-04-18 22:31:33 INFO     Setting up RGB manager
2026-04-18 22:31:33 INFO     Creating schedule
2026-04-18 22:31:33 INFO     Updating schedule
2026-04-18 22:31:33 INFO     Using externally-created display in compass
2026-04-18 22:31:33 INFO     Ready to run
2026-04-18 22:31:33 INFO     Calibrating! Trovastelle
2026-04-18 22:34:32 ERROR    Display raised an OSError in display_calibration_data! This was attempt 0/5
2026-04-18 22:42:55 DEBUG    Using selector: EpollSelector
2026-04-18 22:42:55 INFO     Updating schedule
2026-04-18 22:42:55 INFO     Now displaying observable Pluto
2026-04-18 22:46:34 INFO     Updating schedule
2026-04-18 22:46:34 INFO     Now displaying observable Praesepe (M44)
2026-04-18 22:46:50 ERROR    Display raised an OSError in display_observable_data! This was attempt 1/5
2026-04-18 22:47:48 ERROR    Display raised an OSError in display_observable_data! This was attempt 1/5
```
